### ISSUE TITLE
LCSC API Endpoint

### ISSUE THREAD

**Issue by tmvermilyea** [PartPilotLab/PartPilot#10]
Hey, it looks like the LCSC API endpoint changed from https://wmsc.lcsc.com/wmsc/ to https://wmsc.lcsc.com/ftps/wm, so the autocomplete function is no longer working. app/api/parts/autocomplete/route.ts needs to be updated to fit the new endpoint, just a heads up!

**Comment by LenniM** [comment]
Hey @tmvermilyea, thanks for the heads up! :) The issue got resolved in the commit b5987d1
