### ISSUE TITLE
Bug: Category overview shows duplicated categories

### ISSUE THREAD

**Issue by merspieler** [PartPilotLab/PartPilot#15]
![screenshot-2024-09-04_18:49:27](https://github.com/user-attachments/assets/8ffae7f9-25af-4af1-a0b1-372a8e28f1e6)

As you can see, categories are shown multiple times.

**Comment by LenniM** [comment]
Hey @merspieler, thanks for raising the issue! Are the parts shown, when filtering for a duplicate category, the same?

**Comment by LenniM** [comment]
Hey @merspieler, thank you for raising the issue! The bug has been fixed with #23.
