### ISSUE TITLE
Bug: Automatically generated/imported category with ampersand in name shows no components

### ISSUE THREAD

**Issue by merspieler** [PartPilotLab/PartPilot#19]
With the addition of some MCUs, it added the category `Embedded Processors & Controllers`, if I select this category, nothing shows up, I guess you need to url encode the category name so the part after the ampersand doesn't get taken as a new url  parameter.

**Comment by LenniM** [comment]
Hey @merspieler, the bug has been fixed with #b8d6ed6. Thanks for raising the issue! If there are still problems, then reopen the issue please :)
